# Generated by Django 4.2.2 on 2023-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('options', models.TextField()),
                ('more_info', models.TextField(blank=True)),
                ('demo_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reversed', models.BooleanField()),
                ('isNormal', models.BooleanField()),
                ('num_vals', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('more_info', models.TextField(blank=True)),
            ],
        ),
    ]
