# Generated by Django 4.2.2 on 2023-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="big5cat",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="isBig5",
            field=models.BooleanField(default=False),
        ),
    ]
