# Generated by Django 4.2.2 on 2023-06-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answerValue', models.IntegerField()),
                ('effect', models.IntegerField()),
                ('questionRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='FilterRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('simpleFilterRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterApp.simplefilter')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
    ]
