# Generated by Django 3.1.5 on 2023-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0002_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
