# Generated by Django 4.2.2 on 2023-06-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_val', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answerId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='userApp.answer')),
                ('questionId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='questionApp.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.answer')),
                ('questionId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='questionApp.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
    ]
